[package]
name = "kafka-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
rskafka = "0.5.0"
tokio = { version = "1.41.1", features = ["full"] }
tokio-util = "0.7.12"
